In [76]:
import pandas as pd

In [77]:
import numpy as np

In [78]:
import matplotlib as plt

In [79]:
import seaborn as sns

# Import Dataset

In [80]:
df=pd.read_csv('Womens Clothing E-Commerce Reviews.csv')

In [81]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [83]:
df.shape

(23486, 11)

# Missing Values
Remove missing values in reviews columns with No Review Text

In [84]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [85]:
df[df['Review Text']==""]=np.NaN

In [86]:
df['Review Text'].fillna("No Review",inplace=True)

In [87]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

df['Review Text']

# Define Target(y) and Feature(X)

In [88]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [89]:
X=df['Review Text']

In [90]:
y=df['Rating']

In [91]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

# Train Test Split

In [92]:
from sklearn.model_selection import train_test_split

In [93]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, stratify=y, random_state=112529)

In [94]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

# Get Feature Text conversion to tokens

In [95]:
from sklearn.feature_extraction.text import CountVectorizer

In [96]:
cv=CountVectorizer(lowercase= True, analyzer='word', ngram_range=(2,3),stop_words = 'english', max_features=5000)

In [97]:
X_train = cv.fit_transform(X_train)

In [98]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [99]:
X_test= cv.fit_transform(X_test)

In [100]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# Get Model Train

In [101]:
from sklearn.naive_bayes import MultinomialNB

In [102]:
model=MultinomialNB()

In [103]:
model.fit(X_train,y_train)

MultinomialNB()

# Get Model Prediction

In [104]:
y_pred = model.predict(X_test)

In [105]:
y_pred.shape

(7046,)

In [106]:
y_pred

array([2., 3., 1., ..., 5., 5., 5.])

# Get Probability of each Predicted class

In [107]:
model.predict_proba(X_test)

array([[0.13810762, 0.41761168, 0.16752197, 0.08469827, 0.19206046],
       [0.13121947, 0.14824925, 0.34227927, 0.04980158, 0.32845043],
       [0.81211668, 0.00433967, 0.0697259 , 0.09929896, 0.0145188 ],
       ...,
       [0.03582725, 0.06660584, 0.12226277, 0.21618005, 0.55912409],
       [0.00517162, 0.00097089, 0.00191876, 0.15254747, 0.83939126],
       [0.0112237 , 0.08662272, 0.15814171, 0.1818631 , 0.56214877]])

# Get Model Evaluation 

In [108]:
from sklearn.metrics import confusion_matrix, classification_report

In [109]:
print(confusion_matrix(y_test,y_pred))

[[  15   26   39   52  121]
 [  54   43   93   75  205]
 [ 111   85  127  199  339]
 [ 178  100  193  325  727]
 [ 440  221  322  655 2301]]


In [110]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.02      0.06      0.03       253
         2.0       0.09      0.09      0.09       470
         3.0       0.16      0.15      0.16       861
         4.0       0.25      0.21      0.23      1523
         5.0       0.62      0.58      0.60      3939

    accuracy                           0.40      7046
   macro avg       0.23      0.22      0.22      7046
weighted avg       0.43      0.40      0.41      7046



# Recategories Ratings as Poor (0) and Good(1) 

In [111]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [112]:
df.replace({'Rating' : {1:0, 2:0, 3:0, 4:1, 5:1}},inplace=True)

In [113]:
y=df['Rating']

In [114]:
x=df['Review Text'] 

# Train Test Split

In [115]:
from sklearn.model_selection import train_test_split

In [116]:
X_train,X_test,y_train,y_test= train_test_split(X,y,train_size=0.7,stratify=y,random_state=112529)

In [117]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

# Get Feature Text Conversion to Tokens

In [118]:
from sklearn.feature_extraction.text import CountVectorizer

In [119]:
cv=CountVectorizer(lowercase= True, analyzer='word', ngram_range=(2,3),stop_words = 'english', max_features=5000)

In [120]:
X_train = cv.fit_transform(X_train)

In [121]:
X_test=cv.fit_transform(X_test)

# Get Model Re-Train

In [122]:
from sklearn.naive_bayes import MultinomialNB

In [126]:
model=MultinomialNB()

In [127]:
model.fit(X_train,y_train)

MultinomialNB()

# Get Model Prediction

In [129]:
y_pred = model.predict(X_test)

In [130]:
y_pred.shape

(7046,)

In [131]:
y_pred

array([1., 1., 1., ..., 1., 0., 1.])

# Get Model Evaluation

In [132]:
from sklearn.metrics import confusion_matrix, classification_report

In [133]:
print(confusion_matrix(y_test,y_pred))

[[ 371 1212]
 [1029 4434]]


In [134]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.27      0.23      0.25      1583
         1.0       0.79      0.81      0.80      5463

    accuracy                           0.68      7046
   macro avg       0.53      0.52      0.52      7046
weighted avg       0.67      0.68      0.67      7046

